#!/bin/bash
set -x
CMD=x509-inetd-superserver
RELEASE="Debug"
DIR=$HOME/workspace/x509-inetd-superserver
CMD=$DIR/$RELEASE/$CMD
UID=1000
GID=100
CERTIFICATE="$DIR/certificates/$(hostname --fqdn).pem"
AUTHORITY="$DIR/certificates/authority.crt"
AUTHORIZE=$DIR/ether.d/authorization
PLUGINDIRECTORY=$DIR/facts

PLUGINS=()

for i in $PLUGINDIRECTORY/*; do
     PLUGINS+=( "$PLUGINDIRECTORY/$(basename $i)" )
done

lst=$(IFS=":"; echo "${PLUGINS[*]}")

$CMD -a $AUTHORITY -c $CERTIFICATE -f $AUTHORIZE -d $lst -g $GID -u $UID
